In [1]:
import numpy as np
np.set_printoptions(edgeitems=100, linewidth=100000)

# CREATE NP.ARRAY

In [90]:
a = np.array([1.0, 2.0, 3.0], dtype='int8')
arr = np.array([[9, 8, 7, 6, 7, 0, 2],
                [6, 5, 4, 2, 4, 3, 5],
                [3, 8, 1, 5, 9, 0, 1],
                [2, 0, 1, 2, 7, 8, 8],
                [0, 1, 4, 3, 3, 6, 7],
                [2, 4, 0, 5, 9, 0, 3],
                [3, 2, 1, 4, 5, 3, 1]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3d-array


# INSPECT ARRAY

In [ ]:
arr.shape
arr.ndim
arr.dtype # returns data type of element
arr.nbytes # returns memory size of the whole array
arr.itemsize # returns memory size of one element
arr.size # returns total number of elements
len(arr) # returns number of rows


# ACCESSING

In [ ]:
arr[0, 1] # select element located at 1st row 2nd column
arr[:,1] # select all rows of 2nd column
arr[0, 1:6:2] # [startindex:endindex:stepsize]
arr([0, 1, 7])
arr[[0, 1, 6]] # returns an array with the 1st, 2nd and last rows


# UPDATE ARRAY

In [ ]:
arr[1, 5] = 20
arr[:, 2] = [0, 0, 0, 0, 0, 0, 0] # assigning entire 3rd column to zeros
arr_3d[0][1, 0]
arr_3d[0, 1, 0] # same as above
arr_3d[:, 1, :] = [[0, 0], [0, 0]]


# UNIQUE ARRAYS

In [ ]:
np.identity(5) # returns a 5 x 5 identity matrix
np.zeros(5)
np.zeros([2, 3]) # returns a 2 x 3 zero matrix
np.ones([4, 2, 2], dtype='int32') # returns a 3d array
np.full([3, 3], 99) # np.full( [dimension:rows, dimension:colummns], value )
np.full_like(arr, 4)
a = np.array([1, 2, 3])
r1 = np.repeat(a, 3, axis=0) # axis-rows: 0; axis-cols: 1 
x = np.arange(0, 6, 2) # returns array([0, 2, 4]); (start:0, end:6, step:2)
xp = np.linspace(0, 5, 100) # start:0, stop:5, num-items:100


# RANDOM VALUES

In [ ]:
np.random.rand(4, 2) # returns a 4 x 2 array where Element ~ UNI(0, 1)
np.random.rand(4, 2) * 100
np.random.random_sample([4, 2]) # same as above
np.random.randint(4, 7, size=[3, 3]) # start:4, end not including 7


# ARRAY METHODS

In [ ]:
a = np.array([1, 2, 3])
b = a.copy()
np.isnan(a) # checks if any of the elements are NAs 
np.isinf(a) # checks if any of the elements are infinity
np.diag(arr) # returns the diagonal of arr


# MATHEMATICS

In [ ]:
np.cos(a)
np.pi # returns pi value
a = np.random.rand(5, 5) * 100
a = np.floor(a) # rounds down every element
a = np.ceil(a) # rounds up every element
a = np.round(a)
a[[1, 1, 2], [3, 4, 3]] = np.nan
a[[3, 4, 3], [0, 1, 2]] = np.inf


# LINEAR ALGEBRA

In [ ]:
a = np.ones([2, 3])
b = np.full([3, 2], 2)
c = np.random.randint(0, 10, size=[2, 2])
np.matmul(a, b) # matrix multiplication
a.dot(b) # same as above
np.linalg.multi_dot([a, b, c]) # multiply several matrices
a @ b @ c # same as above

a = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
np.linalg.det(a) # returns the determinant of the matrix
np.linalg.inv(a) # returns the inverse of the matrix
np.trace(a) # returns the sum along the diagonals
np.transpose(a)
v = np.array([1, 2, 3])
w = np.array([0, 2, 1])
np.cross(v, w) # returns the cross product of v and w


# STATISTICS

In [ ]:
s = np.array([[1, 2, 3],
              [4, 5, 6]])
np.min(s, axis=0) # axis-rows: 1; axis-cols: 0


# RESHAPING

In [ ]:
before = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(before)
after = before.reshape([4, 2])
print(after)


# STACKING

In [ ]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
a3 = np.array([9, 0, 1, 0])
np.vstack([a1, a2, a2]) # vertical stack a.k.a row bind
np.hstack([a1, a2]) # horizontal stack a.k.a column bind


# LOAD DATA

In [ ]:
filedata = np.genfromtxt('../numpy_arr.txt', delimiter=',') # reads from .txt file
filedata = filedata.astype('int32')


# BOOLEAN MASKING AND ADVANCED INDEXING

In [ ]:
filedata[filedata > 50]
np.any((filedata > 50) & (filedata < 100), axis=0) # checks if any of the columns have at least 1 element > 50
arr = np.arange(1, 31).reshape([6, 5])
arr[[0, 1, 2, 3], [1, 2, 3, 4]]
arr[[0, 4, 5], 3:5]


# FILTERING

In [ ]:
np.where(filedata > 100)
np.where(np.isinf(a)) # returns row and column index


In [309]:
a = np.random.rand(5, 5) * 100
a = np.floor(a)
a[[1, 1, 2], [3, 4, 3]] = np.nan
a[[3, 4, 3], [0, 1, 2]] = np.inf

print(np.where(np.isinf(a)))
print(np.where(np.isnan(a)))


array([[35., 79., 99., 28., 52.],
       [38., 24., 29., nan, nan],
       [27., 68., 63., nan, 71.],
       [inf, 44., inf, 46., 72.],
       [83., inf, 66., 74., 83.]])

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
196
766
999
