In [166]:
import numpy as np
from numpy import poly1d, exp
import scipy.special, scipy.integrate, scipy.linalg, scipy.fftpack, scipy.stats
from scipy.optimize import minimize
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
np.set_printoptions(edgeitems=100, linewidth=100000)

# POLYNOMIAL

In [ ]:
p = poly1d([3, 6, 8])
p1 = poly1d([1, 2, 3], variable='y')
p.r # returns root of p
poly1d(p) # returns the coefficient of the polynomial
print(p.integ(k = 6)) # integrates polynomial p; k = integration constant (optional)
print(p.deriv()) # differentiates polynomial p

# SciPy SPECIAL FUNCTIONS

In [ ]:
arr = np.arange(1, 11)
scipy.special.cbrt(arr) # returns cube root
scipy.special.exp2(3) # returns 2**3 
scipy.special.radian(30, 10, 50) # agrs: degrees; minutes; seconds
scipy.special.cosdg(30) # returns cosine(30 deg)
scipy.special.perm(6, 2) # returns 6P2
scipy.special.comb(6, 2) # retuns 6C2


# INTEGRATION

In [ ]:
f = lambda x: exp(-x**3)
scipy.integrate.quad(f, 1, 2) # scipy.integrate.quad(func, lower_limit, upper_limit)
# DOUBLE INTEGRATION
f = lambda x, y: x + np.sin(y) + 1
scipy.integrate.dblquad(f, -np.pi, np.pi, lambda y: 0, lambda y: 2) # inner domain: y first then x
f = lambda y, x: x + np.sin(y) + 1
scipy.integrate.dblquad(f, 0, 2, lambda x: -np.pi, lambda x: np.pi) # same as before
f = lambda y, x: x*y**2
scipy.integrate.dblquad(f, 0, 2, lambda x: 0, lambda x: 1) # inner domain: x first then y


# LINEAR ALGEBRA

In [ ]:
a = np.array([[1, 2],
              [3, 4]])
scipy.linalg.det(a) # returns the determinant of the matrix
scipy.linalg.inv(a) # returns the inverse of the matrix
scipy.linalg.eig(a) # returns two arrays: eigenvalues & eigenvectors
b = np.array([[2], [3], [5]])
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 8]])
np.linalg.solve(A, b) # returns solution to linear equation (Ax = b)
v = np.array([1, 2, 3])
w = np.array([0, 2, 1])
np.cross(v, w) # returns the cross product of v and w


# FOURIER TRANSFORMATION

In [ ]:
a = np.array([1, 5, 6, 14, 25, 40])
y = scipy.fftpack.fft(a) # fourier transform
invy = scipy.fftpack.ifft(a) # inverse fourier transform
i = scipy.fftpack.fft(invy) # returns array_a in complex number form


# INTERPOLATION

In [ ]:
x = np.arange(0, 6, 1)
y = np.array([0.1, 0.2, 0.3, 0.5, 1.0, 0.9])
xp = np.linspace(0, 5, 100)
plt.plot(x, y, 'bo')
y1 = interp1d(x, y, kind='linear')
plt.plot(xp, y1(xp), 'r-')
y2 = interp1d(x, y, kind='quadratic')
plt.plot(xp, y2(xp), 'b--')
y3 = interp1d(x, y, kind='cubic')
plt.plot(xp, y3(xp), 'g+')
plt.legend(['Point', 'Linear', 'Quadratic', 'Cubic'])
plt.show()


# STATISTICS

In [ ]:
x_norm = scipy.stats.norm.rvs(size = 5) # returns rvs ~ N(0, 1)
scipy.stats.norm.cdf(np.array([1, -1, 0, 1, 3, 4, -2, 6])) # returns the cdf/area under the curve
scipy.stats.norm.ppf(0.5) # returns the ppf/z-value
arr = np.array([3, 5, 3, 2, 0, 9, 8, 6, 7, 1, 2, 4])
arr.min(); arr.max()
arr.mean()
np.median(arr) # returns the median of the array
scipy.stats.mode(arr) # returns the mode of the array
arr.std(); arr.var()
g = scipy.stats.mstats.gmean([1, 5, 20]) # returns the geometric mean/nth root of the product of n numbers
h = scipy.stats.mstats.hmean([1, 5, 20]) # returns the harmonic mean/reciprocal of the mean of the reciprocals


# SCIENTIFIC CONSTANTS

In [ ]:
scipy.constants.find()
scipy.constants.value('Planck constant')
scipy.constants.pi

# Non Linear Programming

In [256]:
def objective(x):
    x1 = x[0]
    x2 = x[1]
    x3 = x[2]
    x4 = x[3]
    return x1 * x4 * (x1 + x2 + x3) + x3

def constraint1(x):
    return x[0] * x[1] * x[2] * x[3] - 25

def constraint2(x):
    tot = 0
    for i in range(4):
        tot += x[i]**2
    return tot - 40

x0 = [1, 5, 5, 1]
print(objective(x0))

b = (1.0, 5.0)
bnds = (b, b, b, b)
con1 = {'type':'ineq', 'fun':constraint1}
con2 = {'type':'eq', 'fun':constraint2}
cons = [con1, con2]
sol = minimize(objective, x0, method='SLSQP', bounds=bnds, constraints=cons)
print(sol)

16
     fun: 17.01401724556073
     jac: array([14.57227039,  1.37940764,  2.37940764,  9.56415081])
 message: 'Optimization terminated successfully'
    nfev: 25
     nit: 5
    njev: 5
  status: 0
 success: True
       x: array([1.        , 4.74299607, 3.82115466, 1.37940764])


In [259]:
x1 = 1
x4 = 4.74299607
x2 = 3.82115466
x3 = 1.37940764

print(x1*x2*x3*x4)
print(x1**2 + x2**2 + x3**2 + x4**2)


24.9999999509456
40.000000092965536


In [221]:
arr = np.array([[2, 5, 3],
                [4, 0, 8],
                [1, 3, 0]])
v = np.array([-3, 0, 2])

inv = scipy.linalg.inv(arr)
res = np.matmul(inv, v)
x, y, z = res[0], res[1], res[2]

print(2*x + 5*y + 3*z)
print(4*x + 8*z)
print(x + 3*y)


-3.0
0.0
2.0


In [223]:
arr = np.array([[3, 1, 4],
                [5, 9, 2],
                [5, 3, 5]])
v = np.array([1, 6, 8])

inv = scipy.linalg.inv(arr)
res = np.matmul(inv, v)
x, y, z = res[0], res[1], res[2]
print(res, '\n')
print(3*x + 1*y + 4*z)
print(5*x + 9*y + 2*z)
print(5*x + 3*y + 5*z)


[10.61111111 -3.72222222 -6.77777778] 

0.9999999999999964
5.999999999999993
7.999999999999993


In [253]:
a = np.array([[3, 1],
              [0, 2]])
eigv_2 = np.linalg.eig(a)[1][1]
eigv_1 = np.linalg.eig(a)[1][0]

m = np.array([[3-2, 1],
              [0, 2-2]])

eigv1 = np.linalg.eig(a)[1][:,0]
eigv2 = np.linalg.eig(a)[1][:,1]
np.matmul(m, eigv2)


array([0., 0.])

In [254]:
m = np.array([[2, 0],
              [0, 3]])
np.matmul(m, m)

array([[4, 0],
       [0, 9]])